version: '3'
services:
  postgres:
    image: postgres:11.0-alpine
    hostname: postgres
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: s3cr3t

  metabase:
    image: metabase/metabase:v0.30.4
    hostname: metabase
    container_name: metabase
    depends_on:
    - postgres
    ports:
    - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: s3cr3t
      MB_DB_HOST: postgres
      JAVA_TIMEZONE: Europe/Berlin
    